/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "RCC_interface.h"   // RCC (Reset and Clock Control) interface header
#include "GPIO_interface.h"  // GPIO interface header for configuring pins
#include "LCD_Interface.h"   // LCD interface header for controlling the LCD display
#include "KeyPad_Interface.h" // Keypad interface header for reading keypad inputs
#include "GPIO_private.h"    // GPIO private header for accessing low-level GPIO details
#include "FPU.h"             // FPU (Floating Point Unit) header for enabling FPU support
#include "SysTick.h"         // SysTick header for system tick timer
#include "calculator.h"      // Calculator header that contains the core calculator logic

// Main function where the program starts execution
int main(void)
{
    // Configure the system clock to use the external high-speed oscillator (HSE)
    RCC_HSE_Mode(BYPASSED);  // Set HSE mode to bypass external oscillator

    // Enable the HSE (High-Speed External) clock source
    RCC_SetClkStatus(HSE, ON);

    // Configure the PLL (Phase Locked Loop) to multiply the HSE frequency to 80 MHz
    RCC_PLL_Config(80, 4, HSE);  /* Set PLL to 80 MHz */

    // Set the system clock to use the PLL as the main clock source
    RCC_SetSysClk(PLL);          /* Set system clock to PLL */

    // Enable the clock for GPIO ports A, B, and C (used for LCD, keypad, etc.)
    RCC_AHB1_EnableClk(GPIOAEN); /* Enable clock for GPIOA */
    RCC_AHB1_EnableClk(GPIOBEN); /* Enable clock for GPIOB */
    RCC_AHB1_EnableClk(GPIOCEN); /* Enable clock for GPIOC */

    // Enable the Floating Point Unit (FPU) for handling floating-point operations
    EnableFPU();

    // Initialize the keypad for user input
    KEYPAD_init();

    // Configure the pins used by the LCD and initialize it
    LCD_PinConfig();
    LCD_voidInit();

    // Enter the main calculator loop where user input is processed and displayed
    calculatorLoop();

    // Infinite loop to keep the program running (can be replaced by system tasks if necessary)
    while(1);
}
